#!/bin/bash
echo "=== Docker Permission Fix ==="
echo ""
echo "Option 1: Add user to docker group (recommended)"
echo "  sudo usermod -aG docker $USER"
echo "  newgrp docker  # or log out and back in"
echo ""
echo "Option 2: Run with sudo (quick fix)"
echo "  sudo docker-compose up -d"
echo ""
echo "Option 3: Check if Docker is running"
echo "  sudo systemctl status docker"
echo "  sudo systemctl start docker  # if not running"
echo ""
echo "After fixing, run: docker-compose up -d"
