services:
  - type: web
    name: qr-transformer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn web.app:app --host 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

